all:
	$(MAKE) -C basic
	$(MAKE) -C demo

run-simx:
	$(MAKE) -C basic run-simx
	$(MAKE) -C demo run-simx

clean:
	$(MAKE) -C basic clean
	$(MAKE) -C demo clean

clean-all:
	$(MAKE) -C basic clean-all
	$(MAKE) -C demo clean-all
