all:
	$(MAKE) -C basic
	$(MAKE) -C demo
	$(MAKE) -C print
	$(MAKE) -C vecAdd
	$(MAKE) -C assign

run-simx:
	$(MAKE) -C basic run-simx
	$(MAKE) -C demo run-simx
	$(MAKE) -C vecAdd run-simx
	$(MAKE) -C assign run-simx

clean:
	$(MAKE) -C basic clean
	$(MAKE) -C demo clean
	$(MAKE) -C print clean
	$(MAKE) -C vecAdd clean
	$(MAKE) -C assign clean

clean-all:
	$(MAKE) -C basic clean-all
	$(MAKE) -C demo clean-all
	$(MAKE) -C vecAdd clean-all
	$(MAKE) -C assign clean-all
